import { ResultsService } from './result.service';
import { FormControl,FormGroup,Validators } from '@angular/forms';
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, } from "@angular/router";
import { Subscription } from 'rxjs';
import {Observable} from 'rxjs';
import {map, startWith} from 'rxjs/operators';

@Component({
  selector: 'app-resultat',
  templateUrl: './resultat.component.html',
  styleUrls: ['./resultat.component.css']
})
export class ResultatComponent implements OnInit {
  myControl = new FormControl();
  filteredOptions!: Observable<string[]>;
  form!: FormGroup;
  private resultatId: any;
  private routeSub: Subscription | undefined;
  filePreview!: string;
  fileName!:string;
  constructor( public ResultsService:ResultsService,public route: ActivatedRoute ) { }
  gen() {

      let last = Math.floor(Math.random() * (999999 - 100000) + 100000);
      return last.toString();

  }
  private _filter(value: string): string[] {
    const filterValue = value.toLowerCase();

    return this.options.filter(option => option.toLowerCase().includes(filterValue));
  }
  ngOnInit(): void {
    this.filteredOptions = this.myControl.valueChanges.pipe(
      startWith(''),
      map(value => this._filter(value)),
    );
    this.form = new FormGroup({
      object: new FormControl(null, {
        validators: [Validators.required]
      }),
      filePath: new FormControl(null,{
        validators: [Validators.required],
      })
    });

    this.routeSub = this.route.params.subscribe(params => {
      this.resultatId = params['userId'];

    });

  }
  onFilePicked(event: Event) {
    const file =((event.target as HTMLInputElement ).files as FileList)[0];
    this.form.patchValue({ filePath: file });
    ( (this.form.get('filePath') as any ).updateValueAndValidity());
    const reader = new FileReader();
    reader.onload =() => {
      this.filePreview = (reader.result as string );
    };
    reader.readAsDataURL(file);
    this.fileName = file.name;
  }
  onSavePost(){
    if (this.form.invalid){
      return
    }

    this.ResultsService.addresults(
      this.gen(),
      this.form.value.object,
      this.form.value.filePath,
      this.resultatId
      );

  }
  options: string[] = [
    'MNI test: Anticorps heterophiles',
'acide amine essentiel',
'bon cholesterol',
'mauvais cholesterol',
'1-25-dihydroxy-vitamine D (Calcitriol) ',
'17-Hydroxyprogesterone',
'17-OH progesterone',
'17-OHP',
'25 OH vitamine D; 1-25 diOH vitamin D',
'25-hydroxy-vitamine D (Calcidiol)',
'5-HIM',
'-VCA IgM/IgG',
'virus Epstein-Barr',
'du virus Epstein-Barr',
'EAD',
'Al AT; MT',
'Al c',
'MP',
'ACAN',
'ACE',
'Acetaminophen',
'Acetylcholinesterase erythrocytaire',
'Acide 5-hydroxy-indole-acetique',
'Acide longue ou vitamine B9',
'Acide lactique',
'Acide Methylmalonique',
'Acide urique',
'Acide valproique',
'ACTH',
'Activite Anti-Xa',
'Activite et Antigene de l"Anfithrombine',
'Adrenaline (epinephrine)',
'AFP',
'AFP marqueur tumoral',
'Alanine aminotransferase',
'ALAT - TGP',
'Albumine',
'Albumine glyquee (test apparente)',
'Albumine plasmatique',
'Albumine sanguine',
'Albumine serique',
'Albuminemie',
'Alcool',
'Alcool ethylique',
'Aldolase',
'Aldosterone - Renine',
'Alpha-1 Antitrypsine',
'Alpha-foetoproteine',
'AML',
'AMM',
'Ammoniaque',
'Ammoniaque plasmatique',
'Ammoniemie',
'Amylase',
'Amylase plasmatique',
'Amylase urinaire',
'Amylasemie',
'Amylasurie',
'ANA',
'Analyse ADN de la mucoviscidose',
'Analyse d"urine de depistage',
'Analyse de la mutation genetique PSEN1',
'Analyse du LCR',
'Analyse du liquide amniotique; amniocentese',
'Analyse du Liquide Cephalo-Rachidien',
'Analyse du liquide peritoneal',
'Analyse moleculaire pour le diagnostic de mucoviscidose',
'ANCA',
'Anti-ADN double brin',
'Anti-ADN',
'Anticoagulant lupique',
'Anticoagulant lupique',
'Anticorps anti-ADN natif double-brin',
'Anticorps anti-ADNdb',
'Anticorps anti-antigenes nucleaires solubles',
'Anticorps anti-antigenes solubles',
'Anticorps anti-cytoplasme des polynucleaires neutrophiles',
'Anticorps anti-ENA',
'Anticorps anti-M2',
'Anticorps anti-microsome ',
'Anticorps anti-mitochondries',
'Anticorps anti-mitochondries de type M2',
'Anticorps anti-muscles lisses',
'Anticorps anti-neutrophiles cytoplasmiques',
'Anticorps anti-nucleaires',
'Anticorps anti-nucleaires fluorescents (FAN)',
'Anticorps antiphospholipides',
'Anticorps antiphospholipides et cofacteurs',
'Anticorps anti-recepteur de Ia TSH',
'Anticorps anti-recepteur de Ia TSH (TRAK) (TBII)',
'Anticorps anti-streptolysine 0 ',
'Anticorps anti-thyroglobuline ',
'Anticorps anti-thyroglobuline (Ac anti-Tg)',
'Anticorps anti-thyroide',
'Anticorps anti-thyroidiens ',
'Anticorps anti-thyroperoxidase',
'Anticorps anti-thyroperoxidase(Ac anti-TPO)',
'Anticorps anti-Toxoplasma gondii',
'Anticorps anti-transglutaminase (anti-TG); anticorps anti-endomysium ',
'Anticorps anti-VIH',
'Anticorps EBV',
'Anticorps thythosfimulants ',
'Anti-ECT',
'Antigone carcino-embryonnaire ',
'Antigone de cancer 125',
'Antigone de cancer 15-3 ',
'Antigone de cancer 19-9 ',
'Antigone specifique de la prostate ',
'Antistreptotysine 0',
'Anti-Tg',
'Antithrombine',
'Antithrombine III fonctionnelle ',
'Anti-TPO',
'Anti-Xa; inhibition du Xa; heparine anti-facteur Xa',
'Apo A-I',
'Apo B',
'Apo B-100',
'Apolipoproteine A-I',
'Apolipoproteine B-100',
'Appellation par Ieur numero',
'ASAT-TGO',
'ASLO',
'Aspartate aminotransferase',
'Aspiration de moelle osseuse',
'AT III',
'Auto-anticorps thyroidiens ',
'Azote',
'Azotemie',
'B12 & Folates',
'B2M; UM; a2-Microglobuline',
'BAAR : coloration et culture',
'Bacterie responsable de la maladie',
'Bandelettes urinaires ',
'BCR-ABL',
'Beta hCG',
'Beta-2 Microglobuline marqueur tumoral',
'Beta2 Microglobuline ',
'Bicarbonates',
'Bilan du fer',
'Bilan electrolytique ',
'Bilan hepatique',
'Bilan lipidique',
'Bilan martial',
'Bilirubine',
'Bilirubine directe (ou bilirubine conjuguee)',
'Bilirubine indirecte (ou bilirubine non conjuguee)',
'Bilirubine neonatale',
'Bilirubine totale',
'Biomarqueurs de la maladie d"Alzheimer',
'Blennorragie',
'BNP',
'BNP pour peptide natriuretique de type B',
'Bordella pertussis',
'BRCA',
'BRCA-1 et BRCA-2',
'BReast CAncer Gene 1 et 2 — genes du cancer du sein 1 et 2',
'C2H5OH ',
'CA 15-3 ',
'CA 19-9 ',
'CA-125 ',
'Cafeine ',
'Calcemie ',
'Calcitonine',
'Calcium ',
'Calciurie ',
'C-ANCA ',
'Capacite totale de fixation de la transferrine',
'Carbamazepine',
'Carbamazepine totale',
'Carbatrol®',
'Carbohydrate Antigone 125',
'Carbohydrate Antigone 15-3',
'Carbohydrate Antigone 19-9',
'Catecholamines',
'Catecholamines Libres Urinaires',
'Catecholamines plasmatiques',
'Catecholamines urinaires',
'CCMH',
'CD4 - CD8',
'C-erbB-2 ',
'Ceruleoplasmine',
'Caruloplasmine',
'CgA',
'Chaines legeres Kappa et Lambda',
'Chaines legeres libres',
'Chlamydia trachomatis',
'Chlamydiae',
'Cholesterol',
'Cholesterol des lipoproteines de faible densite',
'Cholesterol des lipoproteines de haute densite',
'Cholesterol sanguin',
'Cholesterol total',
'Cholinesterase',
'Chromogranine A',
'Chromosome Philadeiphie (Ph)',
'Ciclosporine',
'Ciclosporine',
'CK',
'CK totale ',
'CK-MB',
'Clairance de la creafinine',
'Clairance de la creafinine mesuthe',
'CLL',
'CLLS',
'Clostridium diflicile',
'Coefficient de saturation de la transferrine',
'Cofacteurs de la coagulation sanguine',
'Coloration de Gram',
'Combinaison de tests pour la recherche d"anticoagulant lupique',
'Inhibiteur Lupique; TCA sensible; TCA-LA; temps de venin de vipere ',
'Russell dilue (TVVRd); temps de venin de vithre Russell modifie ',
'(TVVRm)',
'Comptage des globules rouges',
'Comptage des plaquettes',
'Comptage des thrombocytes',
'Comptage globulaire',
'Comptage T4 - T8',
'Concentration de glucose dans le sang ou Glycernie ou Glucose ',
'sanguin',
'Concentration en CO2',
'Corticotrophine',
'Cortisol ',
'CPK',
'CPK-MB ',
'Croat',
'Creatine Kinase',
'Creatine Kinase—MB',
'Creatine phosphokinase',
'Creatinine',
'CRP',
'CRP haute sensibilite',
'CRP hs',
'CRP ultrasensible',
'CRP us ',
'Cuivre',
'Cuivre (symbole chimique: Cu)',
'Cuivre hepafique',
'Cuivre serique libre',
'Cuivre serique total',
'Cuivre serique uftrafiltrable',
'Cuivre urinaire des 24H',
'Culture de Clostridium ditficile',
'Cystatine C',
'Cystatine C',
'D-dimeres',
'Debit de filtration glomerulaire esfime',
'Depakine',
'Depistage des streptocoques du groupe B',
'Depistage du virus du SIDA',
'Depistage urinaire par bandelettes',
'Depistage VIII',
'Derive proteinique purifie ',
'Derives methoxyles plasmatiques',
'Deshydrogenase lactique',
'Detection des anticorps specifiques par fluorescence',
'Detection par PCR de Toxoplasma gondii ',
'DFG estime',
'Diagnostic biologique de la maladie cceliaque ',
'Diagnostic de la coqueluche',
'Dipeptidyl-dipeptidase A (EC-3.4.15.1) ',
'Dopamine',
'Dosage et ratio des chaines legeres fibres ',
'Dosage quantitatif des immunoglobufines ',
'Dosage serique des chaines legeres fibres ',
'Dosages des cofacteurs',
'EAD',
'EBV test',
'ECA',
'ECBC ',
'ECBU ',
'Electrolytes',
'Electrophorese des proteins',
'Electrophorese des proteins et Immunofixation',
'Electrophorese des proteins seriques',
'Electrophorese des proteins urinaires',
'Enzyme de Conversion de l"Angiotensine',
'Enzyme de conversion de rangiotensine I',
'ERBB2 ',
'Ethanol ',
'Ethanol',
'Etude de l"agregation plaquettaire; etude des fonctions plaquettaires',
'Examen bacteriologique des crachats',
'Examen biochimique et cyto-bacteriologique du LCR',
'Examen cyto-bacteriologique des crachats',
'Examen cytobacteriologique des urines',
'Examen microscopique apt& coloration de Gram',
'Examen parasitologique des selles',
'Exploration dune anomalie lipidique',
'Facteur I',
'Facteur II) ou par leur nom (fibrinogene',
'Facteur Rhumatolde',
'Facteur V Leiden',
'Facteur V Leiden et Mutation G20210/A du gene de la Prothrombine ',
'Facteur Von Willebrand',
'Facteur Von Willebrand anfigene et activite',
'Facteurs de la coagulation',
'Facteurs de risque cardiovasculaire',
'Fe',
'Fer sanguin ',
'Fer serique ',
'Fer total',
'Ferritine',
'Ferritine serique',
'Fibrinogene ',
'Fibronectine foetale',
'Fibronectine foetale',
'Folates erythrocytaires',
'Folliculostimuline ',
'Formule leucocytaire',
'Formule sanguine',
'Formule sanguine au microscope',
'FR',
'Fraction du cuivre serique non fiee a la thruloplasmine',
'Fragments de degradation de la fibrine',
'FRCV',
'Frottis de sang peripherique',
'Frottis sanguin ',
'Fructosamines ',
'FSH',
'FTA qui sont des noms de tests. Treponema pallidum',
'FVW:Ag ; FVW:RCo ; cofacteur de la ristocetine',
'G6PD ',
'G-6-PD ',
'Gamma-glutamyl transferase',
'Gamma-glutamyl transpeptidase',
'Gaz du sang',
'Gaz du sang ar"teriel',
'GDS',
'Gene de fusion bcr-abl',
'Genotypage de depistage de resistance du HIV aux anfiretroviraux ',
'Genotypage de Ia mucoviscidose',
'Genotypage de rapolipoproteine E',
'Genotype de l"Apo E',
'GGT',
'GGTP',
'GH',
'Glucose',
'Glucose-6-Phosphate Dehydrogenase',
'Glythmie',
'Glycemie a jeun ',
'Glycohemoglobine',
'Glycosurie ou Glucose urinaire',
'Gonocoques',
'Gonorrhee',
'Groupage ABO et Rhesus',
'Groupage sanguin ',
'Groupe HLA',
'Groupe sanguin',
'Haptoglobine',
'Hb',
'HbAl c',
'hCG',
'HCG qualitative ',
'HCG quantitative ',
'Hct',
'HDL',
'HDL cholesterol ',
'HDL-C',
'Hematocrite',
'Hernoculture',
'Hemoglobine',
'Hemoglobine A1c',
'Hemoglobine glycosylee',
'Hemoglobine glyquee',
'Hemogramme',
'Hepatite virale A',
'Hepatite virale B',
'Hepatite virale C ',
'Her-2lneu',
'HER-2lneu',
'Hg',
'HIM',
'HLA-1327',
'HLA-1327 aMigene',
'Home tests',
'Homocysteine',
'Homocysteine plasmatique totale ',
'Hormone adthnocorticotrope',
'Hormone chorionique gonadotrope humaine',
'Hormone de croissance ',
'Hormone de croissance (GH)',
'Hormone de croissance humaine (hGH)',
'Hormone folliculo-stimulante ',
'Hormone luteinisante',
'Hormone parathyroidienne ',
'Hormone parathyroidienne ',
'Hormone somatotrope',
'Hp',
'HPT',
'HPV',
'Human epidermal growth factor receptor 2 (Recepteur 2 du facteur',
'de croissance opidermique humain)Amplification du gene Her2/neu',
'par FISH (Hybridation in situ en fluorescence); surexpression Her2',
'par IHC (immunohistochimie) ',
'Human Leukocyte Antigen ',
'Human leukocyte antigen B27',
'Hyperglycemie provoquee par voie orale (HGPO)',
'IDR',
'IgE totales',
'IGF-1 ',
'IgG',
'IgG EA',
'IgG EBNA',
'IgG VCA',
'IgM',
'IgM VCA',
'IgM)',
'IgM/IgG anti-borrelia burgdorferi',
'IMA ',
'Immunoglobulines',
'Immunoglobulines E totales',
'Immunoglobulines totales; Immunoglobuline A (IgA)',
'Immunoglobuline G (IgG) ; Immunoglobuline M (IgM) ',
'Immunophenotypage',
'Indices eryhtrocytaires : VGM, TCMH, CCMH, IDR ',
'Infection par le gonocoque',
'Insuline',
'Insuline-like Growth Factor - 1',
'International Normalized Ratio (INR)',
'Intradermoreaction a la tuberculine',
'Intradermoreaction a la tuberculine (IDR) ou test a la tuberculine lonogramme',
'Ischemia-Modified Albumin (Alburnine modffiee par fischemie) ',
'Isoenzymes de la LDH',
'LA ',
'Lactate',
'Lactate deshydrogenase',
'LD ',
'LDH',
'LDH totale',
'LDL',
'LDL cholesterol',
'LDL-C',
'LH',
'Lipase',
'Lipoprotein (a)',
'Lipoprotein petit a (prononciation) ',
'Liquide amniofique',
'Lithiemie; Nom des so-eclat& : Theralite ',
'Lithium',
'Lp(a)',
'Lupus Anticoagulant',
'Lutecistimuline',
'Lymphocytes CD4-CD8',
'Magnesemie',
'Magnesium',
'Mais aussi Thyreostimuline et Thyreotropine',
'Marqueurs cardiaques',
'Marqueurs seriques de la trisomie 21 au tours du premier trimestre ',
'Marqueurs seriques de la trisomie 21 au second semestre ',
'Marqueurs Trisomie 21 (1er trimestre)',
'Marqueurs Trisomie 21 (2eme trimestre)',
'Marqueurs tumoraux',
'Mercure',
'Metabolite de Ia serotonine',
'Metanephrines fibres plasmatiques',
'Metanephrines plasmatiques',
'Microalbumine',
'Microalbumine urinaire',
'Microalbuminurie',
'Micropakine',
'Mise en culture',
'MNI test',
'MNI-test',
'Moelle osseuse; analyse medullaire',
'Morphologie des globules rouges.',
'MTHFR',
'Mutation du Facteur V Leiden: Resistance a la Proteine C activee',
'Facteur V R5060; Mutation 20210 de la prothrombine: Prothrombine ',
'G20210A; Facteur II 20210',
'Mutation du gene de la methylonetetrahydrofolate Mductase ',
'Mutation du gene de la MTHFR',
'Mutation 020210/A',
'Mutations gene CFTR',
'Mycobacteries : examen microscopique et culture',
'Myelogramme',
'Myoglobine',
'Na',
'Neisseria gonorrhoeae',
'Neurolithium',
'NFS ',
'NGB ',
'Nicotine ou Cotinine',
'NicotinelCotinine',
'Nom de la specialite: Gardenal',
'Nom de la specialite: Rapamune',
'Nom de specialite: Di-Hydan',
'Nom des specialites : Naomi',
'Nom formel : acide delta aminolevulinique (ALA)',
'Nombre de globules rouges; nombre d"erythrocytes',
'Noradrenaline (norepinephrine)',
'NT-proBNP',
'NT-proBNP pour propeptide N-terminal du peptide natriurefique de ',
'type B (en anglais c N-terminal Pro-Brain Natriurefic Peptide x.) ',
'Numerafio',
'Numeration des Globules Blancs',
'Numeration des Globules Rouges',
'Numeration des leucocytes',
'Numeration des leucocytes; nombre de globules blancs',
'Numeration Formule Sanguine',
'Numeration plaquettaire',
'Oestradiol (17 beta oestradiol ou E2) ',
'Oestriol (E3)',
'Oestrogenes',
'Oestrone (El)',
'Osmolalite',
'P',
'PAL ',
'P-ANCA',
'Papillomavirus humain',
'Paracetamol',
'Parathormone',
'PCR',
'Peptide Beta Amyloide 42',
'Peptide-C',
'Peptide-C de l"insuline',
'Phenobarbital',
'Phenylalanine',
'Phenytoine',
'Phosphatase Alcaline',
'Phosphate inorganique',
'Phosphate',
'Phosphore',
'PO4',
'Ponction biopsie modullaire',
'Porphobilinogene (PBG)',
'Porphyrines',
'Potassium',
'Pthalbumine',
'Pthalbumine liant la thyroxine',
'Prealbumine riche en tryptophane',
'Preseniline 1',
'PRL ',
'ProBNP',
'Profil electrolytique ',
'Progesterone',
'Progesterone',
'Prolactine',
'Prolactine serique ',
'Proteine S',
'Proteine C',
'Proteine C Fonctionnelle ou Antigone',
'Proteine C-reactive',
'Proteine C-reactive ultrasensible',
'Proteine fixant l"hemoglobine',
'Proteine S Libre (Fonctionnelle) ou Antigone (Totale)',
'Proteine Tau',
'Proteines glyquees plasmatiques',
'Proteines seriques totales',
'Proteines totales ',
'Proteinurie',
'Proteinurie des 24H ',
'Proteinurie totale',
'Prothrombine)comme indique dans le tableau ci-dessous.',
'PSA',
'PSA complexe',
'PSA libre',
'PSA total',
'PSEN',
'Pseudocholinesterase (butylcholinesterase) serique',
'PTH',
'PTH intacte',
'Ratio Albumine/Globulines ',
'Ratio Albumine/Globulines ',
'Ratio Proteinurie! Cthatininurie',
'Recherche Tun portage de SARM',
'Recherche d"un portage de Staphylococcus aureus Resistant a la ',
'Methicilline (SARM)',
'Recherche dune infection a Clostridium difficile',
'Recherche Tanficorps anti-VHA',
'Recherche Tanficorps contre Borrelia burgdorferi',
'Recherche de bacilles acido-alcoolo-resistants (BAAR)',
'Recherche de drogues illicites',
'Recherche de mycobacteries',
'Recherche des mutations du gene CFTR',
'Recherche des toxines A et B de Clostridium difficile. coproculture ',
'Recherche du bacille de Koch (BK)',
'Recherche etiologique dune diarrhee Oh- ou post-antibiotherapie ',
'Recherche etiologique dune gastro-enterite virale.',
'Reticulocytes',
'RPR',
'Sandimmun',
'S-DHEA',
'Sensibilite aux antibiotiques',
'Sensibilite aux antimicrobiens',
'Serodiagnostic de la rubeole',
'Serodiagnostic de la syphilis (ex BW)',
'Serologie',
'Serologie anti-Bordetella pertussis IgA',
'Serologie EBV',
'Serologie Hepatite A ',
'Serologie Hepatite B ',
'Serologie Hepatite C ',
'Serologie Maladie Cceliaque',
'Serologie Maladie de Lyme',
'Serologie Rubeole ',
'Serologie Toxoplasme ',
'Sideremie',
'Siderophylline',
'Sirolimus',
'Sodium',
'Somatomedine C ',
'Somatotropine ',
'Streptococcus agalactiae',
'Streptococcus pyogenes',
'Streptocoque bfita-hemolytique du groupe A',
'Streptocoque du groupe A',
'Streptocoques beta-hemolytiques du groupe B',
'Streptocoques du groupe B',
'Streptotest',
'Suivi therapeufique',
'Sulfate de Dehydroepiandrosterone',
'Sulfate de DHEA ',
'Syphili',
'Systeme renine-angiotensine-aldosterone',
'T3',
'T3 Libre (T3L)',
'T3 Totale (T3T)',
'T4',
'T4 Libre (T4L)',
'T4 Totale (T4T) ',
'Tau/M.42',
'Taux de Prothrombine (TP)',
'Taux d"hoparine ',
'TCA',
'TCMH',
'TCO2',
'Tegreto10',
'Temps de cephaline active',
'Temps de Cephaline plus Activateur',
'Temps de Prothrombine',
'Temps de Quick',
'Test de diagnostic rapide (TDR)',
'Test de diagnostic rapide des angines',
'Test de grossesse',
'TGP',
'Theophylline',
'Theophylline et Cafeine',
'Thyroglobuline',
'Thyroglobuline (Tg)',
'Thyroid Stimulating Hormone (Hormone stimulant la thyroide) ',
'Thyrotropine (le plus souvent)',
'Thyroxine ',
'Total CO2 ',
'Toxoplasma gondii',
'TP',
'TPHA',
'Transaminase glutamo-oxaloacetique',
'Transaminase glutamo-pyruvique serique',
'Transferrine ',
'Transthyretine',
'TRIG',
'Triglythrides',
'Triiodothyronine',
'Troponine',
  ];

}
